### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by sodqeyounes** [hama3254/Crunchyroll-Downloader-Android#1]
I normally browse the site, but when I try to log in, this page appears!
![Screenshot_2020-06-18-20-09-58-432_com hama crdl](https://user-images.githubusercontent.com/8031530/85051179-dafab000-b19f-11ea-9055-16a78d896e22.jpg)

**Comment by hama3254** [comment]
i'm currently don't work on the Android Version.
you can take a look on this alternativ, it uses my backround code with a new and better UI.
https://github.com/hyugogirubato/Crunchyroll-DL
